## Pandas

**Alunos**:

- **Pedro Henrique Paz Sobral**
- **Wodson Fernando Oliveira da Silva**
- **Roselene Maria Botelho Rocha**

### Instalação do Pandas

In [ ]:
# Alternativa 1
!pip install pandas # alternative: conda install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Introduzindo Séries de Dados do Pandas

1 - Importe as bibliotecas pandas e numpy com os aliases 'pd' e 'np', respectivamente.

In [ ]:
import pandas as pd
import numpy as np

2 - Utilize o numpy para criar um array com 10 elementos de números inteiros aleatórios entre 50 e 100. Em seguida, transforme-o em uma série do pandas e a exiba.

In [ ]:
# Insira a resposta abaixo.

array1 = np.random.randint(50,101,(10))
series1 = pd.Series(array1)
display(series1)

0    95
1    65
2    86
3    96
4    63
5    63
6    90
7    87
8    55
9    77
dtype: int64

3 - Utilize a função range do Python para criar uma série do Pandas contendo 10 elementos cujos índices sejam uma sequência ascendente de números ímpares  e os valores sejam uma sequência descendente de números inteiros de 10 a 1. Em seguida, converta o tipo numérico da série criada para 'int32' e exiba a série.

In [ ]:
# Insira a resposta abaixo.
lista = []
for i in range(0,11):
  if i % 2 != 0:
    lista.append(i)
print(lista)

[1, 3, 5, 7, 9]

In [ ]:
series2 = pd.Series((lista), dtype='Int32')

series2.sort_values(inplace=True,ascending=False)
display(series2)

4    9
3    7
2    5
1    3
0    1
dtype: Int32

4 - Abaixo são definidos dois dicionários contendo capitais brasileiras com a população estimada para os anos de 2000 e 2018. Utilize ambos os dicionários definidos abaixos para criar dois objetos do tipo Series.

In [ ]:
populacao2010 = {'São Paulo': 10405867, 'Rio de Janeiro': 5851914, 'Salvador': 2440828, 'Belo Horizonte':2232747, 'Fortaleza':2138234	}
populacao2018 = {'São Paulo': 12176866, 'Rio de Janeiro': 6688927, 'Brasília': 2974703, 'Salvador': 2857329, 'Fortaleza': 2643247}

# Insira a resposta abaixo.


novapop10 = pd.Series(populacao2010)
novapop18 = pd.Series(populacao2018)

In [ ]:
display(novapop10)

São Paulo         10405867
Rio de Janeiro     5851914
Salvador           2440828
Belo Horizonte     2232747
Fortaleza          2138234
dtype: int64

In [ ]:
display(novapop18)

São Paulo         12176866
Rio de Janeiro     6688927
Brasília           2974703
Salvador           2857329
Fortaleza          2643247
dtype: int64

#### Operações Aritméticas com Séries

5 - Crie uma nova série contendo a diferença entre as populações de 2018 e 2010.

In [ ]:
# Insira a resposta abaixo.

subpop = novapop18-novapop10
display(subpop)

Belo Horizonte          NaN
Brasília                NaN
Fortaleza          505013.0
Rio de Janeiro     837013.0
Salvador           416501.0
São Paulo         1770999.0
dtype: float64

6 - Crie uma nova série contendo a média entre as duas séries iniciais.

In [ ]:
# Insira a resposta abaixo.
media = (novapop18 + novapop10) / 2
display(media)

Belo Horizonte           NaN
Brasília                 NaN
Fortaleza          2390740.5
Rio de Janeiro     6270420.5
Salvador           2649078.5
São Paulo         11291366.5
dtype: float64

### Introduzindo Dataframes

7 - Crie um dicionário cujas chaves sejam: 2010, 2018, 'diferenca', 'media'. Utilize como valores as séries correspondentes criadas nas questões anteriores. Utilize esse dicionário para criar um dataframe.

In [ ]:
# Insira a resposta abaixo.

df = pd.DataFrame({'2010':populacao2010,'2018':populacao2018,'diferenca':subpop,'media':media}, axis = 1)
display(df)

TypeError: DataFrame.__init__() got an unexpected keyword argument 'axis'

8 - Desta vez, crie um dataframe equivalente ao criado na questão anterior concatenando as quatro séries (referentes a 2000, 2018, diferença e média). Lembre-se de inserir os mesmos títulos para as colunas.

In [ ]:
# Inserir a resposta abaixo.
dfmasterblaster =  pd.concat ([novapop10,novapop10,subpop,media], axis=1,)
display(dfmasterblaster)

In [ ]:
dfmasterblaster.rename({0:'2000',1:'2018',2:'diferenca',3:'média'},axis=1,inplace=True)
display(dfmasterblaster)

In [ ]:
help(pd.concat)

9 - Adicione uma nova coluna ao dataframe anterior chamada 2019, esta deve conter um acréscimo de 50000 sobre os valores da coluna 2018.

In [ ]:
# Insira a resposta abaixo.
ano2019 = novapop18+50000
display(ano2019)
novapop19 = pd.Series(ano2019)

In [ ]:
novodf = pd.concat([dfmasterblaster,novapop19], axis=1)
novodf.rename({0:'2019'}, axis=1, inplace=True)
display(novodf)

10 - Exiba somente os dados referentes a Salvador.

In [ ]:
# Insira a resposta abaixo.
novodf.iloc[2]

11 - Exiba ** terceira linha** do dataframe utilizando o seu posicionamento no dataframe.

In [ ]:
# Insira a resposta abaixo.
novodf.iloc[3]

12 - Exiba as **três primeiras linhas** do dataframe a partir da posição.

In [ ]:
# Insira a resposta abaixo
novodf.head(3)

13 - Remova a coluna 2019 criada anteriormente.

In [ ]:
# Insira a resposta abaixo.
novodf.drop(columns=['2019'], inplace=True)
display(novodf)

14 - Remova os registros que apresentam valores nulos.

In [ ]:
# Insira a resposta abaixo.
# The 'Belo Horizonte' row was not dropped here because only its 'diferenca' and 'média' columns
# were NaN, not all columns.
limpo = novodf.dropna(axis=0, how='all')
display(limpo)

In [ ]:

limpo.drop(labels=['Belo Horizonte'], axis=0, inplace = True)
display(limpo)

### Exercícios com base de dados fictícia (toy dataset)

Execute o bloco de código abaixo para realizar o download de uma pequena base de dados que será utilizada para os próximos experimentos. A base de dados poderá ser acessada através do arquivo toy_dataset.csv. Caso a sessão se encerre, re-execute essa célula de código.

15 - Execute a leitura do Toy Dataset diretamente em um dataframe.

> O toy dataset foi disponibilizado em conjunto com o notebook.

In [ ]:
# Insira a resposta abaixo.

16 - Exiba o tipo de dados de cada coluna do dataframe.

In [ ]:
# Insira a resposta abaixo.
df = pd.read_csv('toy_dataset.csv')

df.dtypes

Number       int64
City        object
Gender      object
Age          int64
Income     float64
Illness     object
dtype: object

17 - Utilize a função .head() para exibir o cabeçalho do dataframe e assim conhecer as colunas, o índice e as linhas iniciais da base de dados.

In [ ]:
# Insira a resposta abaixo.
df.head()

   Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

18 - Realize as seguintes operações:

- Adicione uma nova coluna chamada NumberAge e que apresente a soma entre os valores da coluna Number com os valores da coluna Age.
- Exiba o cabeçalho do dataframe resultante.
- Remova a coluna NumberAge.
- Exiba o cabeçalho do dataframe resultante.

In [ ]:
# Insira a resposta abaixo.
df['NumberAge']=(df['Number']+df['Age'])
df.head()
df.drop(columns=['NumberAge'])

        Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
1            2  Dallas    Male   54   45084.0      No
2            3  Dallas    Male   42   52483.0      No
3            4  Dallas    Male   40   40941.0      No
4            5  Dallas    Male   46   50289.0      No
...        ...     ...     ...  ...       ...     ...
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

[150000 rows x 6 columns]

19 - Realize as seguintes operações a partir do dataframe definido anteriormente:

- Exiba as cinco primeiras linhas do dataframe, todos os atributos devem ser apresentados com exceção do primeiro e último.

- Exiba as cinco últimas linhas do dataframe, exiba somente o atributo City.

In [ ]:
# Insira a resposta abaixo.
somente5 = df[['City','Gender','Age','Income']]
somente5.head(5)

     City Gender  Age   Income
0  Dallas   Male   41  40367.0
1  Dallas   Male   54  45084.0
2  Dallas   Male   42  52483.0
3  Dallas   Male   40  40941.0
4  Dallas   Male   46  50289.0

In [ ]:
cidade= df[['City']]
cidade.tail(5)

          City
149995  Austin
149996  Austin
149997  Austin
149998  Austin
149999  Austin

20 - Ordene de forma ascendente as amostras utilizando como critério o salário anual. Em seguida, resete os índices dos registros.

In [ ]:
# Insira a resposta abaixo.
df_ordenado = df.sort_values('Income', ascending=False)
display(df_ordenado)

        Number           City  Gender  Age    Income Illness  NumberAge
109350  109351  Mountain View    Male   58  177157.0      No     109409
105281  105282  Mountain View    Male   41  176746.0      No     105323
109060  109061  Mountain View    Male   61  173991.0      No     109122
110877  110878  Mountain View    Male   52  173826.0      No     110930
112192  112193  Mountain View    Male   58  172825.0      No     112251
...        ...            ...     ...  ...       ...     ...        ...
17135    17136         Dallas  Female   39    3842.0      No      17175
9298      9299         Dallas  Female   31    2667.0     Yes       9330
18484    18485         Dallas  Female   43    2474.0      No      18528
7896      7897         Dallas  Female   34     584.0      No       7931
245        246         Dallas  Female   40    -654.0     Yes        286

[150000 rows x 7 columns]

**21 - Defina a coluna 'Number' como o índice do dataframe. Em seguida, exiba do segundo até o quinto registro a partir do posicionamento.**

In [ ]:
# Insira a resposta abaixo.
df.set_index('Number')

          City  Gender  Age    Income Illness  NumberAge
Number
1       Dallas    Male   41   40367.0      No         42
2       Dallas    Male   54   45084.0      No         56
3       Dallas    Male   42   52483.0      No         45
4       Dallas    Male   40   40941.0      No         44
5       Dallas    Male   46   50289.0      No         51
...        ...     ...  ...       ...     ...        ...
149996  Austin    Male   48   93669.0      No     150044
149997  Austin    Male   25   96748.0      No     150022
149998  Austin    Male   26  111885.0      No     150024
149999  Austin    Male   25  111878.0      No     150024
150000  Austin  Female   37   87251.0      No     150037

[150000 rows x 6 columns]

In [ ]:
df.iloc[2:6]

   Number    City  Gender  Age   Income Illness  NumberAge
2       3  Dallas    Male   42  52483.0      No         45
3       4  Dallas    Male   40  40941.0      No         44
4       5  Dallas    Male   46  50289.0      No         51
5       6  Dallas  Female   36  50786.0      No         42

22 - Desta vez, exiba os registros com Number variando de 2 até 5 a partir do próprio rótulo Number.

In [ ]:
# Insira a resposta abaixo.
df[(df['Number'] > 2) & (df['Number'] <  7)]

   Number    City  Gender  Age   Income Illness  NumberAge
2       3  Dallas    Male   42  52483.0      No         45
3       4  Dallas    Male   40  40941.0      No         44
4       5  Dallas    Male   46  50289.0      No         51
5       6  Dallas  Female   36  50786.0      No         42

23 - Qual a cidade e o gênero da pessoa com a maior renda (Income)?

In [ ]:
# Insira a resposta abaixo.
display(df)
otodf = df.sort_values('Income', inplace=True, ascending=False)

        Number    City  Gender  Age    Income Illness  NumberAge
0            1  Dallas    Male   41   40367.0      No         42
1            2  Dallas    Male   54   45084.0      No         56
2            3  Dallas    Male   42   52483.0      No         45
3            4  Dallas    Male   40   40941.0      No         44
4            5  Dallas    Male   46   50289.0      No         51
...        ...     ...     ...  ...       ...     ...        ...
149995  149996  Austin    Male   48   93669.0      No     150044
149996  149997  Austin    Male   25   96748.0      No     150022
149997  149998  Austin    Male   26  111885.0      No     150024
149998  149999  Austin    Male   25  111878.0      No     150024
149999  150000  Austin  Female   37   87251.0      No     150037

[150000 rows x 7 columns]

24 - Quantas pessoas moram na cidade de Dallas?

In [ ]:
# Insira a resposta abaixo.
df['City'].value_counts()
#19707

City
New York City      50307
Los Angeles        32173
Dallas             19707
Mountain View      14219
Austin             12292
Boston              8301
Washington D.C.     8120
San Diego           4881
Name: count, dtype: int64

25 - Qual a idade média das pessoas que estão doentes? Utilize o atributo Illness para obter essa informação.

In [ ]:
# Insira a resposta abaixo.
idade_media = df[df['Illness'] == 'Yes']['Age']
media_idade = idade_media.mean()
print(f'{media_idade:.2f}')

45.02

26 - Quantas pessoas tem um salário anual maior que R$ 30000?

In [ ]:
# Insira a resposta abaixo.
df[df['Income'] > 30000]

        Number           City  Gender  Age    Income Illness  NumberAge
109350  109351  Mountain View    Male   58  177157.0      No     109409
105281  105282  Mountain View    Male   41  176746.0      No     105323
109060  109061  Mountain View    Male   61  173991.0      No     109122
110877  110878  Mountain View    Male   52  173826.0      No     110930
112192  112193  Mountain View    Male   58  172825.0      No     112251
...        ...            ...     ...  ...       ...     ...        ...
14412    14413         Dallas  Female   42   30013.0      No      14455
6561      6562         Dallas  Female   43   30006.0      No       6605
13406    13407         Dallas  Female   27   30003.0      No      13434
3342      3343         Dallas  Female   51   30002.0      No       3394
17478    17479         Dallas  Female   54   30001.0      No      17533

[148218 rows x 7 columns]

27 - Quantas pessoas estão doentes?

In [ ]:
# Insira a resposta abaixo.
df['Illness'].value_counts()

Illness
No     137861
Yes     12139
Name: count, dtype: int64

# 28 - Quantas pessoas estão doente e apresentam renda (Income) menor que 35000 ou maior que 50000?

In [ ]:
# Insira a resposta abaixo.
doentesricos = df[(df['Illness'] == 'Yes') & ((df['Income'] < 35000) | (df['Income'] > 50000))].shape[0]
display(doentesricos)

11386

In [ ]:
df.query('Illness == "Yes" & Income < 35000 | Income > 50000')

        Number           City  Gender  Age    Income Illness  NumberAge
109350  109351  Mountain View    Male   58  177157.0      No     109409
105281  105282  Mountain View    Male   41  176746.0      No     105323
109060  109061  Mountain View    Male   61  173991.0      No     109122
110877  110878  Mountain View    Male   52  173826.0      No     110930
112192  112193  Mountain View    Male   58  172825.0      No     112251
...        ...            ...     ...  ...       ...     ...        ...
12007    12008         Dallas  Female   57   12043.0     Yes      12065
18665    18666         Dallas  Female   55   11301.0     Yes      18721
17820    17821         Dallas  Female   57    9760.0     Yes      17878
9298      9299         Dallas  Female   31    2667.0     Yes       9330
245        246         Dallas  Female   40    -654.0     Yes        286

[137043 rows x 7 columns]

#29 - Mostre os registros que apresentam a menor idade encontrada e uma renda entre 40000 e 42000.

In [ ]:
df.query('Age > 60 & Income > 40000 & Income < 42000' )

       Number    City  Gender  Age   Income Illness  NumberAge
14403   14404  Dallas  Female   62  41993.0      No      14466
12434   12435  Dallas  Female   64  41991.0      No      12499
8071     8072  Dallas  Female   65  41990.0      No       8137
2332     2333  Dallas  Female   61  41988.0      No       2394
16936   16937  Dallas  Female   61  41949.0      No      16998
...       ...     ...     ...  ...      ...     ...        ...
18725   18726  Dallas    Male   63  40044.0      No      18789
3341     3342  Dallas    Male   64  40020.0      No       3406
2726     2727  Dallas  Female   61  40019.0      No       2788
17661   17662  Dallas  Female   63  40016.0      No      17725
2191     2192  Dallas  Female   63  40007.0      No       2255

[145 rows x 7 columns]

#30 - Mostre os registros referentes a cidade de Dallas que apresentam a maior idade e que estão doentes.

In [ ]:
df.query('City == "Dallas" & Age > 60 & Illness == "Yes"')

       Number    City  Gender  Age   Income Illness  NumberAge
153       154  Dallas    Male   63  71551.0     Yes        217
16731   16732  Dallas    Male   62  70728.0     Yes      16794
10858   10859  Dallas    Male   63  70212.0     Yes      10922
1382     1383  Dallas    Male   62  70194.0     Yes       1445
12423   12424  Dallas  Female   61  69251.0     Yes      12485
...       ...     ...     ...  ...      ...     ...        ...
10289   10290  Dallas  Female   62  22568.0     Yes      10352
14436   14437  Dallas  Female   65  20732.0     Yes      14502
1940     1941  Dallas  Female   61  18531.0     Yes       2002
4185     4186  Dallas  Female   61  17720.0     Yes       4247
1683     1684  Dallas  Female   61  17003.0     Yes       1745

[201 rows x 7 columns]